#ifndef ITEM_ENUMS_H_
#define ITEM_ENUMS_H_

typedef enum rarity {
	NULL_RARITY,
	COMMON,
	UNCOMMON,
	RARE,
	EPIC,
	LEGENDARY
} rarity_t;

typedef enum value_type {
	VALUE_TYPE_NONE,
	VALUE_TYPE_ARMOR,
	VALUE_TYPE_WEAPON,
	VALUE_TYPE_SPELL,
	VALUE_TYPE_FOOD,
	VALUE_TYPE_SCROLL
} value_type_t;

typedef enum armor_type {
	NULL_ARMOR_TYPE,
	LIGHT,
	MEDIUM,
	HEAVY
} armor_type_t;

// names should be limited to 32 characters
typedef enum item_ids {
	
	// items
	BLANK,
	TELEPORT_SCROLL,
	HEALTH_POTION,
	APPLE,
	ROTTEN_APPLE,
	CHICKEN_DINNER,
	RAT_MEAT,
	DRAGONFIRE_JERKY,
	CELESTIAL_CORNBREAD,
	NIGHTBLOOM_GRAPES,
	PIZZA,
	BEAR_CHILI,
	
	// oil
	OIL,
	
	// heavy armors
	BLACKSTONE_ARMOR,
	BRONZE_ARMOR,
	IRON_ARMOR,
	STEEL_ARMOR,
	MITHRIL_ARMOR,
	SOULCRUST_ARMOR,
	TERRACITE_ARMOR,
	GRAVEMARROW_ARMOR,
	VOIDMARROW_ARMOR,
	
	// medium armors
	RAT_HIDE_ARMOR,
	SLIME_ARMOR,
	BOG_IRON_ARMOR,
	BONE_ARMOR,
	SUNSTEEL_ARMOR,
	FALSE_IRON_ARMOR,
	BARKMAIL_ARMOR,
	DRAGON_BONE_ARMOR,
	
	// light armors
	CLOAK,
	LEATHER_CLOAK,
	BOGSTICK_VEST,
	VOIDLACE_CLOACK,
	
	// swords
	BLACK_STONE_SWORD,
	BRONZE_SWORD,
	IRON_SWORD,
	STEEL_SWORD,
	MITHRIL_SWORD,
	SOULCRUST_SWORD,
	TERRACTIE_SWORD,
	GRAVEMARROW_SWORD,
	VOIDMARROW_SWORD,
	
	// spears
	BLACK_STONE_SPEAR,
	BRONZE_SPEAR,
	IRON_SPEAR,
	STEEL_SPEAR,
	MITHRIL_SPEAR,
	SOULCRUST_SPEAR,
	TERRACTIE_SPEAR,
	GRAVEMARROW_SPEAR,
	VOIDMARROW_SPEAR,
	
	// maces
	BLACK_STONE_MACE,
	BRONZE_MACE,
	IRON_MACE,
	STEEL_MACE,
	MITHRIL_MACE,
	SOULCRUST_MACE,
	TERRACTIE_MACE,
	GRAVEMARROW_MACE,
	VOIDMARROW_MACE,
	
	// axes
	BLACK_STONE_AXE,
	BRONZE_AXE,
	IRON_AXE,
	STEEL_AXE,
	MITHRIL_AXE,
	SOULCRUST_AXE,
	TERRACTIE_AXE,
	GRAVEMARROW_AXE,
	VOIDMARROW_AXE,
	
	// pickaxes
	BLACK_STONE_PICKAXE,
	BRONZE_PICKAXE,
	IRON_PICKAXE,
	STEEL_PICKAXE,
	MITHRIL_PICKAXE,
	SOULCRUST_PICKAXE,
	TERRACTIE_PICKAXE,
	GRAVEMARROW_PICKAXE,
	VOIDMARROW_PICKAXE,
	
	// bows
	BLACK_STONE_BOW,
	BRONZE_BOW,
	IRON_BOW,
	STEEL_BOW,
	MITHRIL_BOW,
	SOULCRUST_BOW,
	TERRACTIE_BOW,
	GRAVEMARROW_BOW,
	VOIDMARROW_BOW,
	
	// staffs
	BLACK_STONE_STAFF,
	BRONZE_STAFF,
	IRON_STAFF,
	STEEL_STAFF,
	MITHRIL_STAFF,
	SOULCRUST_STAFF,
	TERRACTIE_STAFF,
	GRAVEMARROW_STAFF,
	VOIDMARROW_STAFF,

	// spells
	FIREBALL_SPELL_BOOK,
} item_ids_t;

#endif
